# Generated by Django 2.2.8 on 2021-07-16 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
