# Generated by Django 2.2.8 on 2021-07-18 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210718_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
